[project]
name = "mtgprices"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=3.0.5",
    "streamlit>=1.63.0",
    "streamlit-searchbox>=0.1.24",
]

[project.scripts]
mtgprices = "mtgprices:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
